
<script>
if(id==8 || id==19 || id==20 || id==28 || id==52 || id==29){
		  $('#winterwaerinputs').show();
	  }else{
		  $('#winterwaerinputs').hide();
	  }
	  if(id==9){
		  $('#personalcareappliancesinputs').hide();
	  }else{
		  $('#personalcareappliancesinputs').show();
	  }
	  if(id==10){
		  $('#smartwatchesinputs').show();
	  }else{
		  $('#smartwatchesinputs').hide();
	  }
	  if(id==11){
		  $('#footwareinputs').show();
		  $('#personalcareappliancesinputs').show();
		  $('#size_color').show();
	  }else{
		  $('#footwareinputs').hide();
	  }
	  if(id==12 || id==13 || id==14 || id==16 || id==17){
		  $('#womensaccessoriesinputs').show();
	  }else{
		  $('#womensaccessoriesinputs').hide();
	  } 
	  if(id==15){
		  $('#jwelleryinputs').show();
	  }else{
		  $('#jwelleryinputs').hide();
	  }
	  if(id==50){
		  $('#womenswatchesinputs').show();
	  }else{
		  $('#womenswatchesinputs').hide();
	  } 
	  if(id==22){
		  $('#mensaccessoriesinputs').show();
	  }else{
		  $('#mensaccessoriesinputs').hide();
	  }
	  if(id==51){
		  $('#mensehinicwearinputs').show();
	  }else{
		  $('#mensehinicwearinputs').hide();
	  }
	  if(id==23 || id==25){
		  $('#mensfabricsinputs').show();
	  }else{
		  $('#mensfabricsinputs').hide();
	  } 
	  if(id==30){
		  $('#mobileaccessoriesinputs').show();
	  }else{
		  $('#mobileaccessoriesinputs').hide();
	  } 
	  if(id==34){
		  $('#camerainputs').show();
	  }else{
		  $('#camerainputs').hide();
	  }
	  if(id==35){
		  $('#tabletsinputs').show();
	  }else{
		  $('#tabletsinputs').hide();
	  }
	  if(id==36){
		  $('#routersinputs').show();
		   $('#size_color').hide();
	  }else{
		  $('#routersinputs').hide();
		   $('#size_color').hide();

	  } 
	  if(id==39){
		  $('#laptopsinputs').show();
	  }else{
		  $('#laptopsinputs').hide();

	  }
	  if(id==40){
		  $('#mobilesinputs').show();
	  }else{
		  $('#mobilesinputs').hide();

	  } 
	   
	</script>